### ISSUE TITLE
你好，耳机外放切换的值不会算哦

### ISSUE THREAD

**Issue by RockJesus** [athlonreg/AppleALC-ALCPlugFix#2]
设定值是8位的一个二进制数，记作a7 a6 a5 a4 a3 a2 a1 a0，推算出此二进制数之后，四四拆分转换为2位的十进制数加1即为此设定值

a7表示enabled。 a6=0，没具体应用，不用管。 a5~a0，存放tag。**

这部分看不懂，请问怎么算出82的？

**Comment by fengluoye** [comment]
我也看到这里，不过我拿例子中的数据验证了一下，算的和例子不太一样啊。
例子里面有用的数据：
enable=1
tag=01

设定值
a7=1
a6=0
a5a4=a3a2=a1a0=01
最后整合的数据就是：10010101
四四分组：1001 0101
转换为10进制：95
最终的设定值不是应该为96吗？是不是我哪里理解错了。。。

**Comment by Xc2333** [comment]
== 并不是“a5a4=a3a2=a1a0=01”，a5-a0应该是000001，所以最后的数据是1000 0001 ，十进制81，加1=82。
   ## 请认真复习二进制

**Comment by momoxionger** [comment]
enable=1
tag=01

设定值
a7=1
a6=0
a5~a0，存放tag
等价于a5a4a3a2a1a0=01,不足的位数用0补足,所以 a5a4a3a2a1=00001最后整合的数据就是：最后整合的数据就是：10000001
四四分组：1000 0001
转换为10进制：81
最终的设定82
@fengluoye 
@RockJesus
