### ISSUE TITLE
老哥 图床挂了 能不能重新写下readme

### ISSUE THREAD

**Issue by holoto** [athlonreg/AppleALC-ALCPlugFix#3]
推荐你使用免费图床 很稳定
https://imgchr.com/

**Comment by frankiezdh** [comment]
铜球

**Comment by athlonreg** [comment]
不好意思，刚看到你们的反馈，这个帖子有些看了，建议看黑果小兵的帖子，地址如下
https://blog.daliansky.net/Use-AppleALC-sound-card-to-drive-the-correct-posture-of-AppleHDA.html

**Comment by athlonreg** [comment]
> 推荐你使用免费图床 很稳定
> https://imgchr.com/

非常抱歉，刚才已经修复

**Comment by athlonreg** [comment]
> 铜球

非常抱歉，刚才已经修复
